# Generated by Django 3.2.7 on 2021-09-12 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 19, 55, 6, 99733, tzinfo=utc)),
        ),
    ]
